version: 2

models:
  - name: int_stackoverflow_answers
    description: ""
    columns:
      - name: _pk
        description: ""
        tests:
          - unique
          - not_null

      - name: id
        description: ""

      - name: title
        description: ""

      - name: body
        description: ""

      - name: accepted_answer_id
        description: ""

      - name: answer_count
        description: ""

      - name: comment_count
        description: ""

      - name: community_owned_datetime_utc
        description: ""

      - name: creation_datetime_utc
        description: ""

      - name: favorite_count
        description: ""

      - name: last_activity_datetime_utc
        description: ""

      - name: last_edit_datetime_utc
        description: ""

      - name: last_editor_display_name
        description: ""

      - name: last_editor_user_id
        description: ""

      - name: owner_display_name
        description: ""

      - name: owner_user_id
        description: ""

      - name: parent_id
        description: ""

      - name: post_type_id
        description: ""

      - name: score
        description: ""

      - name: tags
        description: ""

      - name: view_count
        description: ""

      - name: organization_name
        description: ""

  - name: int_stackoverflow_questions
    description: ""
    columns:
      - name: _pk
        description: ""
        tests:
          - unique
          - not_null

      - name: id
        description: ""

      - name: title
        description: ""

      - name: body
        description: ""

      - name: accepted_answer_id
        description: ""

      - name: answer_count
        description: ""

      - name: comment_count
        description: ""

      - name: community_owned_datetime_utc
        description: ""

      - name: creation_datetime_utc
        description: ""

      - name: favorite_count
        description: ""

      - name: last_activity_datetime_utc
        description: ""

      - name: last_edit_datetime_utc
        description: ""

      - name: last_editor_display_name
        description: ""

      - name: last_editor_user_id
        description: ""

      - name: owner_display_name
        description: ""

      - name: owner_user_id
        description: ""

      - name: parent_id
        description: ""

      - name: post_type_id
        description: ""

      - name: score
        description: ""

      - name: tags
        description: ""

      - name: view_count
        description: ""

      - name: organization_name
        description: ""