version: 2

models:
  - name: int_github
    description: "Joined intermediate table from staging Github and intermediate Company details / Google Sheet"
    columns:
      - name: _pk
        description: "Primary key"
        tests:
          - unique
          - not_null

      - name: repository_account
        description: "Repository account"

      - name: repository_name
        description: "Repository name"

      - name: user_id
        description: "User ID"

      - name: event_id
        description: "Event ID"

      - name: type
        description: "FollowEvent, PushEvent, WatchEvent, CreateEvent, MemberEvent, ForkEvent, IssuesEvent"

      - name: organization_name
        description: "Organization name"

      - name: created_at_datetime_utc
        description: "Time of creation"