version: 2

models:
  - name: stg_github
    description: "Columns description source: https://github.com/igrigorik/gharchive.org/blob/master/bigquery/schema.js"
    columns:
      - name: _pk
        description: "Primary key"
        tests:
          - unique
          - not_null

      - name: type
        description: "FollowEvent, PushEvent, WatchEvent, CreateEvent, MemberEvent, ForkEvent, IssuesEvent"

      - name: is_public
        description: "Public booleans true or false"

      - name: repo_id
        description: "Repository ID"

      - name: repo_name
        description: "Repository name"

      - name: repo_url
        description: "Repository url"

      - name: actor_id
        description: "Actor's ID"

      - name: actor_login
        description: "Actor's username"

      - name: actor_gravatar_id
        description: "Actor's gravatar ID"

      - name: actor_avatar_url
        description: "Actor's avatar url"

      - name: actor_url
        description: "Actor's url"

      - name: org_id
        description: "Organization's ID"

      - name: org_login
        description: "Organization's login username"

      - name: org_gravatar_id
        description: "Organization's gravatar ID"

      - name: org_avatar_url
        description: "Organization's avatar url"

      - name: org_url
        description: "Organization's url"

      - name: created_at_datetime_utc
        description: "Time of creation in UTC"

      - name: id
        description: "Event ID"

      - name: other
        description: "Unknown fields related to event"