version: 2

sources:
  - name: stackoverflow
    description: BigQuery Public Data - https://console.cloud.google.com/bigquery?project=bigquery-public-data&page=project
    database: bigquery-public-data
    schema: stackoverflow
    tables:
      - name: posts_questions
      - name: posts_answers